<div class="container mb-5">
	<form method="GET">
		<div class="row">
			<div class="col">
				<input type="text" name="type" class="form-control" placeholder="Heuristic">
			</div>
			<div class="col">
				<input type="text" name="value" class="form-control" placeholder="Value">
			</div>
		<div class="col">
			<button type="submit" class="btn btn-primary">Search</button>
		</div>
		</div>
	</form>
</div>