<div class="container mt-3">
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="chartkick.js"></script>
<div id="chart-1" style="height: 300px;"></div>
<script>
	new Chartkick.LineChart("chart-1", <?=json_encode($chartData) ?>)
</script>
<?php
foreach ($flagsByDay as $date => $flags) {
	foreach ($flags as $flag) {
		?>
		<div class="d-flex justify-content-around " id="post_<?=$flag['answer_id']?>">
			<div>Flagged answer: <a href="https://stackoverflow.com/a/<?=$flag['answer_id']?>" class="postID"><?=$flag['answer_id']?></a></div>
			<div><a href="<?=REPORT_URL.'?id='.$flag['report_id']?>"><b>Report link</b></a></div>
			<div><b>Date:</b> <?=$flag['created_at']?></div>
		</div>
		<?php
	}
	?>
	<div class="mt-3">
		<?=$date?> count: <?=$chartData[$date]?>
	</div>
	<hr>
	<?php
}
?>
	<nav aria-label="Page navigation" class="mt-3 d-flex justify-content-center">
	<ul class="pagination">
	<?php if ($page > 1): ?>
		<li class="page-item"><a class="page-link" href="?<?=http_build_query(array_merge($_GET, ['page' => $page - 1])); ?>">Previous</a></li>
	<?php endif;

	for ($i = max(1, $page - 5); $i <= min($maxPage, $page + 5); $i++) {
		echo '<li class="page-item"><a class="page-link" href="?'.http_build_query(array_merge($_GET, ['page' => $i])).'">'.$i.'</a></li>';
	}

	if ($page < $maxPage): ?>
		<li class="page-item"><a class="page-link" href="?<?=http_build_query(array_merge($_GET, ['page' => $page + 1])); ?>">Next</a></li>
	<?php endif; ?>
	</ul>
	</nav>
</div>